# Generated by Django 4.2.13 on 2024-09-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cat_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='toy',
            new_name='toys',
        ),
    ]
